export const BAIRROS_JF: string[] = [
  'Aeroporto',
  'Alto dos Passos',
  'Alto Sumaré',
  'Bairu',
  'Bandeirantes',
  'Barbosa Lage',
  'Barão do Retiro',
  'Barreira do Triunfo',
  'Benfica',
  'Boa Vista',
  'Bom Clima',
  'Bom Pastor',
  'Bomba de Fogo',
  'Bonfim',
  'Borboleta',
  'Bosque do Imperador',
  'Botanágua',
  'Caiçaras',
  'Carlos Chagas',
  'Cascatinha',
  'Centenário',
  'Centro',
  'Cerâmica',
  'Cesário Alvim',
  'Costa Carvalho',
  'Cruzeiro de Santo Antônio',
  'Democrata',
  'Distrito Industrial',
  'Dom Bosco',
  'Eldorado',
  'Esplanada',
  'Estrela Sul',
  'Fábrica',
  'Filgueiras',
  'Floresta',
  'Francisco Bernardino',
  'Grajaú',
  'Grama',
  'Graminha',
  'Granbery',
  'Granjas Bethânia',
  'Granjas Santo Antônio',
  'Igrejinha',
  'Industrial',
  'Ipiranga',
  'JK',
  'Jardim Casablanca',
  'Jardim Glória',
  'Jardim Natal',
  'Jardim Olímpia',
  'Jardim do Sol',
  'Jóquei Clube',
  'Ladeira',
  'Linhares',
  'Manoel Honório',
  'Mariano Procópio',
  'Marmelos',
  'Martelos',
  'Marumbi',
  'Meggliolário',
  'Milho Branco',
  'Monte Castelo',
  'Morro da Glória',
  'Morro do Imperador',
  'Mundo Novo',
  'Muçunge da Grama',
  'Nossa Senhora Aparecida',
  'Nossa Senhora de Fátima',
  'Nossa Senhora de Lourdes',
  'Nova Benfica',
  'Nova Califórnia',
  'Nova Era',
  'Novo Horizonte',
  'Novo Triunfo',
  'Ozanan',
  'Paço del Rey',
  'Paineiras',
  'Parque Guarani',
  'Parque das Torres',
  'Paula Lima',
  'Ponte Preta',
  'Poço Rico',
  'Previdenciários',
  'Progresso',
  'Quintas das Avenidas',
  'Remonta',
  'Represa',
  'Sagrado Coração de Jesus',
  'Salvaterra',
  'Santa Catarina',
  'Santa Cecília',
  'Santa Cruz',
  'Santa Efigênia',
  'Santa Helena',
  'Santa Luzia',
  'Santa Rita de Cássia',
  'Santa Teresa',
  'Santa Terezinha',
  'Santo Antônio',
  'Santo Antônio do Paraibuna',
  'Santos Dumont',
  'Serra D\'Água',
  'São Benedito',
  'São Bernardo',
  'São Dimas',
  'São Geraldo',
  'São Mateus',
  'São Pedro',
  'São Sebastião',
  'Teixeiras',
  'Valadares',
  'Vale do Ipê',
  'Vale dos Bandeirantes',
  'Verbo Divino',
  'Vila Alpina',
  'Vila Furtado de Menezes',
  'Vila Ideal',
  'Vila Olavo Costa',
  'Vila Ozanan',
  'Vivendas do Retiro',
  'Vitorino Braga',
]
